<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="2" time="0.174" timestamp="2022-02-10T23:41:03.035975" hostname="LAPTOP-T7N088FK"><testcase classname="test_Calculator" name="test_add_0_0" file="test_Calculator.py" line="3" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="test_Calculator" name="test_add_0_1" file="test_Calculator.py" line="8" time="0.001"><failure message="assert 0 == 1">def test_add_0_1() :
        calculator = Calculator()
        answer = calculator.add(0,1)
&gt;       assert answer == 1
E       assert 0 == 1

test_Calculator.py:12: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>