<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.159" timestamp="2022-02-10T23:33:56.563792" hostname="LAPTOP-T7N088FK"><testcase classname="test_Calculator" name="test_add_0_0" file="test_Calculator.py" line="3" time="0.001"><failure message="TypeError: 'module' object is not callable">def test_add_0_0() :
&gt;       calculator = Calculator()
E       TypeError: 'module' object is not callable

test_Calculator.py:5: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>